# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-06-03 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
